### ISSUE TITLE
Posting to instagram not working because of token 

### ISSUE THREAD

**Issue by rluin** [roshanpty/instamirror#1]
![instapost](https://user-images.githubusercontent.com/46446426/50768527-67096800-1289-11e9-96f0-8245e80c930c.png)
It gives me an error concerning the token. 
Any ideas?

**Comment by roshanpty** [comment]
This seem to be an issue with the InstagramAPI. Did you get a successful login in the std out for instagram when you initiated the script?

**Comment by roshanpty** [comment]
Closing the issue as it doesn't seem to be associated with the code in this repo.
